from langchain_community.utilities import SQLDatabase
from langchain.chains import create_sql_query_chain
from langchain_google_genai import ChatGoogleGenerativeAI
from sqlalchemy import create_engine

# Database connection parameters
db_user = "root"
db_password = "root123"
db_host = "localhost"
db_name = "retail_sales_db"

# creating SQLAlchemy engine
engine = create_engine(f"mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}")

# initialize SQLDatabase
db = SQLDatabase(engine, sample_rows_in_table_info=3)
print(db.table_info)

# initialize LLM
llm = ChatGoogleGenerativeAI(model="gemini-1.5-pro",
                             api_key="YOUR_API_KEY",
                             temprature=0, max_tokens=None, timeout=None,
                             max_retries=2)
chain = create_sql_query_chain(llm, db)

question = "How many customers are there"
print(f"Asked Question: {question}\n")

# Generate SQL query from question
response = chain.invoke({"question": question})

print(f"Query Generated by LLM: {response}\n")

# Execute the query
result = db.run(response)

print(f"Result after executing query:     {result}")
